server:
  port: 8000

spring:
  application:
    name: SplitEase
  cache:
    type: redis
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/splitease
    username: saurabh
    password: saurabh123
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: SplitEase
    version: 1.0.0

jwt:
  secret: "rA06z6243sjYX79/xEfz7NIA2e9N0Vo9EmA693t1/vM="